const IsoAgLib::iVtObject_c::iVtObjectFillAttributes_s iVtObjectflaContentBg_sROM = {25000,2, 229, NULL, 0,NULL};
const IsoAgLib::iVtObject_c::iVtObjectFillAttributes_s iVtObjectflaFalse_sROM = {65498,2, 12, NULL, 0,NULL};
const IsoAgLib::iVtObject_c::iVtObjectFillAttributes_s iVtObjectflaOk_sROM = {65501,2, 40, NULL, 0,NULL};
const IsoAgLib::iVtObject_c::iVtObjectFillAttributes_s iVtObjectflaLogo_sROM = {65519,0, 2, NULL, 0,NULL};
