const uint8_t iVtObjectmacroChangeMaskAbout_aMacro_Commands [8] = {0xAD, 0, 0, 236, 3, 0xFF, 0xFF, 0xFF};
const IsoAgLib::iVtObject_c::iVtObjectMacro_s iVtObjectmacroChangeMaskAbout_sROM = {252, 8, iVtObjectmacroChangeMaskAbout_aMacro_Commands};
const uint8_t iVtObjectmacroChangeMaskTecu_aMacro_Commands [8] = {0xAD, 0, 0, 233, 3, 0xFF, 0xFF, 0xFF};
const IsoAgLib::iVtObject_c::iVtObjectMacro_s iVtObjectmacroChangeMaskTecu_sROM = {254, 8, iVtObjectmacroChangeMaskTecu_aMacro_Commands};
const uint8_t iVtObjectmacroChangeMaskTimePos_aMacro_Commands [8] = {0xAD, 0, 0, 232, 3, 0xFF, 0xFF, 0xFF};
const IsoAgLib::iVtObject_c::iVtObjectMacro_s iVtObjectmacroChangeMaskTimePos_sROM = {255, 8, iVtObjectmacroChangeMaskTimePos_aMacro_Commands};
