const IsoAgLib::repeat_vtLanguage_s ivtObjectwsTutorialDisplay_aLanguage [] = {{{'d', 'e'}}, {{'e', 'n'}}};
const IsoAgLib::repeat_iVtObject_x_y_iVtObjectFontAttributes_row_col_s iVtObjectwsTutorialDisplay_aObject_x_y_font_row_col [] = {{&iVtObjectosWsDesc, -3, 11, NULL ,0, 0}};
const IsoAgLib::iVtObject_c::iVtObjectWorkingSet_s iVtObjectwsTutorialDisplay_sROM = {0, 1, 1, &iVtObjectdmAbout, 1, iVtObjectwsTutorialDisplay_aObject_x_y_font_row_col, 0,NULL, 2,ivtObjectwsTutorialDisplay_aLanguage};
