const IsoAgLib::iVtObject_c::iVtObjectMeter_s iVtObjectmtrDirection_sROM = {17000, 136, 9, 1, 15, 8, 36, 45, 45, 0, 360, NULL, 0, 0,NULL};
const IsoAgLib::iVtObject_c::iVtObjectMeter_s iVtObjectmtrHitch_sROM = {17002, 62, 20, 0, 0, 13, 9, 68, 112, 0, 90, &iVtObjectnvHitchAngleTarget, 70, 0,NULL};
const IsoAgLib::iVtObject_c::iVtObjectMeter_s iVtObjectmtrSpeed_sROM = {65522, 56, 19, 0, 0, 13, 30, 0, 90, 0, 300, &iVtObjectnvSpeedReal, 0, 0,NULL};
